# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  growthbackend:
    image: growthbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000

  growth_db:
    image: postgres:latest
    container_name: growth_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=GrowthDB
    ports:
      - 5432:5432
    volumes: 
      - ./containers/database:/var/lib/postgresql/data
